- hosts: "controller"
  vars:
  user: "{{user}}"
  sudo : yes
  tasks:
    - name : create sources directory
      file : path=/home/jenkins/repos state=directory owner=jenkins group=jenkins
    - name : clone tiny project
      git: repo=https://github.com/Willymontaz/tinyapp dest=/home/jenkins/repos/tinyapp bare=yes
    - name : change owner to jenkins
      command : chown -R jenkins:jenkins /home/jenkins/repos
    - name : chmod for full access on jenkins repos
      command : chmod -R 777 /home/jenkins/
