- hosts: 
  - controller
  - webapp
  vars:
  user: "{{ user }}"
  sudo : yes
  tasks:
  - name: Download epel rpm
    yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
  - name: Install packages
    yum: name=$item state=installed
    with_items:
      - curl
      - bind-utils
      - fail2ban
      - htop
      - iotop
      - xz-devel
      - pcre-devel
      - openssl
      - pkgconfig
      - vim
      - zlib-devel
      - yum
      - git
