---
# vagrant.yml
- hosts: all
  user: vagrant
  sudo: True
  tasks:
  - name: Install jdk
    yum: name=java-1.7.0-openjdk state=installed
  - name: Install jdk (devel)
    yum: name=java-1.7.0-openjdk-devel state=installed
  - name: Add yum repo jenkins 
    get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest="/etc/yum.repos.d/jenkins.repo"
  - name: Add rpm key for jenkins
    rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  - name: Copy maven configuration for jenkins
    copy: src=jenkins/hudson.tasks.Maven.xml dest=/var/lib/jenkins/hudson.tasks.Maven.xml owner=jenkins group=jenkins
  - name: Install git jenkins plugin
    get_url: url="https://updates.jenkins-ci.org/download/plugins/git/2.0/git.hpi" dest="/var/lib/jenkins/plugins/" 
  - name: Change git plugin owner
    file: path=/var/lib/jenkins/plugins/git.hpi owner=jenkins group=jenkins
  - name: Install jenkins
    yum: name=jenkins state=installed
    notify:
      - restart jenkins
  - name: Install jenkins cli
    get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/var/lib/jenkins/ 
  handlers:
  - name: restart jenkins
    service: name=jenkins state=restarted
