---
- hosts: controller
  user: "{{ user }}"
  sudo: True
  tasks:
  - name: Create archive directory
    file: path=/home/{{user}}/archives owner={{user}} group={{user}} state=directory
  - name: Download maven
    get_url: url="http://apache.websitebeheerjd.nl/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz" dest="/home/{{user}}/archives"
  - name: Install maven
    command: tar xzvf /home/{{user}}/archives/apache-maven-3.1.1-bin.tar.gz creates=/opt/maven chdir=/opt/  
  - name: Create link to maven
    file: path=/opt/maven src=/opt/apache-maven-3.1.1/ state=link
